---
- name: Configure linux workstation
  hosts: localhost
  become: true

  vars_files:
    - config.yaml

  tasks:
    - import_tasks: tasks/cleanup.yaml
    - import_tasks: tasks/repos.yaml
    - import_tasks: tasks/packages_install.yaml
    - import_tasks: tasks/flatpak.yaml
    - import_tasks: tasks/dev.yaml
    - import_tasks: tasks/gnome.yaml
      when: desktop_environment == "gnome"
    - import_tasks: tasks/dotfiles.yaml
