---
- name: Configure linux workstation
  hosts: localhost
  become: true

  vars_files:
    - vars/main.yaml

  tasks:
    - import_tasks: tasks/cleanup.yaml
    - import_tasks: tasks/repos.yaml
    - import_tasks: tasks/packages_install.yaml
    - import_tasks: tasks/flatpak.yaml
    - import_tasks: tasks/vscodium.yaml
    - import_tasks: tasks/gnome.yaml
