---
- name: Configure linux workstation
  hosts: localhost
  become: true

  vars_files:
    - config.yaml

  tasks:
    - import_tasks: tasks/cleanup.yaml
    - import_tasks: tasks/packages_install.yaml
    - import_tasks: tasks/flatpak.yaml
    - import_tasks: tasks/dotfiles.yaml
    - import_tasks: tasks/dev.yaml
    - import_tasks: tasks/kde.yaml
    - import_tasks: tasks/steam.yaml
